<script setup>
import { reactive } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth.js'
const auth = useAuthStore(); const route = useRoute(); const router = useRouter()
const form = reactive({ email: 'student@skala.com', password: '1234' })
async function submit() { if (await auth.login(form.email, form.password)) await router.replace(typeof route.query.redirect === 'string' ? route.query.redirect : '/dashboard') }
function account(admin = false) { form.email = admin ? 'admin@skala.com' : 'student@skala.com'; form.password = admin ? 'admin1234' : '1234' }
</script>
<template><section class="auth-page"><div class="auth-intro"><span>AUTHENTICATION PRACTICE</span><h1>Pinia Store로<br>JWT 로그인 익히기</h1><p>Mock API가 서명한 토큰을 발급하고 Pinia가 인증 상태를 관리합니다.</p><ol><li>인증정보 POST</li><li>서버 인증·JWT 생성</li><li>토큰과 프로필 저장</li></ol></div><form class="login-card" @submit.prevent="submit"><b>POST · /api/auth/login</b><h2>로그인</h2><div class="quick"><button type="button" @click="account()">수강생 계정</button><button type="button" @click="account(true)">관리자 계정</button></div><label>이메일<input v-model.trim="form.email" type="email" required></label><label>비밀번호<input v-model="form.password" type="password" required></label><p v-if="auth.errorMessage" class="error">{{ auth.errorMessage }}</p><button class="submit" :disabled="auth.isLoading">{{ auth.isLoading ? '인증 요청 중…' : 'Mock API로 로그인' }}</button><small>student@skala.com / 1234</small></form></section></template>
<style scoped>.auth-page{display:grid;grid-template-columns:1.1fr .9fr;min-height:560px;border-radius:22px;overflow:hidden;background:#fff;box-shadow:0 14px 40px #17324d18}.auth-intro{padding:54px;background:linear-gradient(145deg,#12304a,#0b7666);color:#fff}.auth-intro span{font-size:.72rem;letter-spacing:.15em;color:#80e0ca}.auth-intro h1{font-size:2.3rem;line-height:1.2}.auth-intro p{color:#d1e5e3}.auth-intro ol{display:grid;gap:12px;padding-left:22px;margin-top:35px}.login-card{align-self:center;padding:42px}.login-card>b{color:#0d8a72;font-size:.8rem}.login-card h2{font-size:2rem}.login-card label{display:grid;gap:7px;margin:16px 0;font-weight:700}.login-card input{padding:13px;border:1px solid #cbd7df;border-radius:9px;font:inherit}.quick{display:flex;gap:8px}.quick button{border:0;padding:8px 10px;border-radius:8px;cursor:pointer}.submit{width:100%;padding:13px;border:0;border-radius:9px;background:#0d8a72;color:#fff;font-weight:700;cursor:pointer}.login-card small{display:block;text-align:center;margin-top:15px;color:#738391}.error{color:#c03543}@media(max-width:720px){.auth-page{grid-template-columns:1fr}.auth-intro,.login-card{padding:30px}}
</style>
